os: linux
dist: bionic
language: node_js
node_js:
  - "12"
cache: yarn
install:
  - yarn global add gatsby-cli
  - yarn install
script:
  - yarn clean
  - yarn prod
deploy:
  provider: script
  script: yarn deploy
  cleanup: false
  on:
    branch: master
