os: linux
dist: bionic
language: node_js
node_js:
  - "12"
cache: yarn
before_script:
  - npm install -g gatsby-cli
deploy:
  provider: script
  script: yarn run deploy
  cleanup: true
  on:
    branch: master
